### ISSUE TITLE
Create SAMPLE file

### ISSUE THREAD

**Issue by philparadis** [micro222/chatbot#15]
Create a SAMPLE file with a SAMPLE dialogue with the bot, that showcases how it works and most features it supports, so that a complete beginner could get started using it easily.

**Comment by philparadis** [comment]
I prefer that Guy does this, since I'm still learning. In fact, such a file would be of tremendous use to me and shouldn't take more than half an hour to create.

**Comment by micro222** [comment]
How about the wiki page named "a quick demo"?

**Comment by philparadis** [comment]
Even better, that's where it out to be with a link from the front page. It sure helps to have 2 brains working on the same project :+1: 

By the way, I would be very grateful if you could write it, it would help me get up to speed. Also, if you have some time to meet someday (maybe at the drone racing event, if you go), perhaps you could explain the overall architecture and idea behind the program to allow me to learn it faster and better?

**Comment by micro222** [comment]
It's already written, along with 3 other wiki pages
