### ISSUE TITLE
Making use of templates.txt

### ISSUE THREAD

**Issue by micro222** [micro222/chatbot#2]
The file isn't currently being used. The functions needed for each sentence type is currently being selected by a list of if/else statements in main.c. The function template_search() when compete, will use the information in templates.txt instead.

**Comment by philparadis** [comment]
Is there a way to assign this task to me? I'm almost sure github allows you to do that.

**Comment by philparadis** [comment]
Okay, I figured it out!

**Comment by philparadis** [comment]
"assign to self" button on the right

**Comment by micro222** [comment]
I've made several changes and put them in templates2.txt, The most recent change is arranging the parameters to look like a function call.

**Comment by micro222** [comment]
I've abandoned the idea. It was too limiting. I have a better idea I'm working on.
