### ISSUE TITLE
Crash when typing "what color is a dog"

### ISSUE THREAD

**Issue by philparadis** [micro222/chatbot#20]
>what color is a dog
I'm not familiar with that kind of sentence

Process returned 0 (0x0)   execution time : 3.721 s
Press ENTER to continue.

**Comment by philparadis** [comment]
For some reason, current behavior is to exit when a sentence cannot be understood (yet it does not exit when a single word is not understood). Changed behavior to not exit when sentence cannot be parsed by adding a continue statement on line 515.

**Comment by micro222** [comment]
I recently added "return 0" before the end of the main loop. I should have placed it after the end. That was the cause. I'll move it.
