### ISSUE TITLE
move functions out of main

### ISSUE THREAD

**Issue by micro222** [micro222/chatbot#7]
The functions in main should be moved to a separate file.

**Comment by philparadis** [comment]
I'll create a phil-refactor branch and once I'm done, I'll make a pull request. I'll let you review it / edit it if you like and then approve and merge it. How does that sound?

We should agree on some coding standards. Is there a certain style that you prefer? What indent size do you want? 2, 3 or 4 spaces?

I like 4 for readability, but that's just me. If you don't have a huge screen it can lead to lots of wrapping. I'm good with 2 spaces too.

**Comment by micro222** [comment]
That sounds good to me.

I haven't given much thought to standards. I'm open to suggestion. I do prefer that the code be readable to a beginner to C or programming in general. To that end, I prefer longer function and variable names and lots of comments.

I'm leaning towards 3 spaces because it's a bit of a middle ground. I'm fine with 4 as well. I don't mind if it differs from one function to another.

**Comment by philparadis** [comment]
I agree with all the above. Will work on this,

**Comment by micro222** [comment]
i moved them to functions.c
